server:
  type: LOBBY                                    # Server type to be authorized by the backend (Eg: LOBBY / GAME / SPECIAL / BUNGEE)
  cluster: 0123456789abcdefg                     # Cluster that will continue as authorization for the backend
  realm: "default"
  sandbox: true                                  # Will not verify sessions and directly grants access to the server for developing purposes
  cross-teleport: true                           # Will allow teleport requests to be cross-server
  fallback: "main-lobby"                         # Will store as fallback when re-login
game:
  running: 0                                     # Max games running at one (Only applies at GAME mode)
  total: 0                                       # Max game running at server lifecycle (Only applies at GAME mode)
  mode: 0123456789abcdefg                        # Database ID of the desired game
  subMode: 0123456789abcdefg                     # Database ID of the desired SubGameMode
  lobby:
    x: 0
    y: 0
    z: 0
api:
  route: "https://perseus.astrocube.net/api/"    # Base path to be called
  connect: 1200                                  # Connect Timeout
  read: 1200                                     # Read Timeout
  retry: 1                                       # Retry Timeout
  threads: 2                                     # Max number of thread pools (According to CPU allowance)
authentication:
  enabled: true                                  # Will enable authentication system at server
  spawn:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
admin:
  punishments:
    reasons:
    - name: "Gei"
      type: "BAN"
  teleport:
    disabled:
      - ""
ban-reasons:
  reason-1:
    slot: 11
    name: "&cMisbehavior"
    lore:
      - "&fThe player is"
      - "&fmisbehaving!"
    punish-reason: "You're behaving bad!"
  reason-2:
    slot: 13
    name: "&cYou don't know"
    lore:
      - "&fBan with not reason, but you like"
      - "&fOk? Perfect."
    punish-reason: "You has been banned without reason, gay."
  reason-3:
    slot: 15
    name: "&cYou don't know, but x2"
    lore:
      - "&fDo you need another explanation?"
      - "&fNice, good day!"
    punish-reason: "You has been banned without reason, but get happy, the reason is same as the first!"
kick-reasons:
  reason-1:
    slot: 11
    name: "&cMisbehavior"
    lore:
      - "&fThe player is"
      - "&fmisbehaving!"
    punish-reason: "You're behaving bad!"
  reason-2:
    slot: 13
    name: "&cYou don't know"
    lore:
      - "&fKick with not reason, but you like"
      - "&fOk? Perfect."
    punish-reason: "You has been kicked without reason, gay."
  reason-3:
    slot: 15
    name: "&cYou don't know, but x2"
    lore:
      - "&fDo you need another explanation?"
      - "&fNice, good day!"
    punish-reason: "You has been kicked without reason, but get happy, the reason is same as the first!"
warn-reasons:
  reason-1:
    slot: 11
    name: "&cMisbehavior"
    lore:
      - "&fThe player is"
      - "&fmisbehaving!"
    punish-reason: "You're behaving bad!"
  reason-2:
    slot: 13
    name: "&cYou don't know"
    lore:
      - "&fWarn with not reason, but you like"
      - "&fOk? Perfect."
    punish-reason: "You has been warned without reason, gay."
  reason-3:
    slot: 15
    name: "&cYou don't know, but x2"
    lore:
      - "&fDo you need another explanation?"
      - "&fNice, good day!"
    punish-reason: "You has been warned without reason, but get happy, the reason is same as the first!"